### ISSUE TITLE
dual checkin fails or travelynx

### ISSUE THREAD

**Issue by djerun** [Traewelldroid/traewelldroid#337]
**Describe the bug**
On tryind to perform a dual checkin it works on traewelling but throws an unspecified error for travelynx

**To Reproduce**
1. go to https://travelynx.de/account
2. click on "Generieren" under API in the "Travel" row
3. copy the uuid
4. go to travelynx under Check-in providers in traewelldroid settings
5. paste uuid
6. check "Enable check-in by default"
7. keep "Enable check-in by default" enabled for traewelling
8. go to home and perform a check-in
9. see check-in success for traewelling and generic error for travelynx

**Expected behavior**
check-in success for traewelling and travelynx

**Desktop (please complete the following information):**
 - Version 2.7.0 (F-Droid)

**Additional context**
since the api error message is not shown and since I saw #334, I tried finding something in the code to see if I could spot any issue with handling the token but neither my kotlin nor my android foo is up to speed so
> WTF u doin

**Comment by jheubuch** [comment]
Hi,

did you copy all parts of the token and paste it without any blanks, spaces, ...?

I'm using "dual check-in" all the time and it's working for me

**Comment by djerun** [comment]
> did you copy all parts of the token and paste it without any blanks, spaces, ...?
yes

> I'm using "dual check-in" all the time and it's working for me
when I noticed I was told by others who used traewelldroid pre-fdroid that it never worked for them. they also told me checking if a string is a valid uuid is trivial in kotlin

my main issue is not having any debug info

**Comment by jheubuch** [comment]
Fair enough, but: According to the issue title and error text the main problem is that the travelynx check-in fails. I asked whether you copied/pasted the token correctly which could fix the problem. Why don't you try or at least answer?

Sidenote: the travelynx tokens are no UUIDs because of the user id prefix. If any of them are thinking that this validation is trivial, PRs are welcome to the project at any time. All I can tell is that the travelynx check-in is working for me (and at least 3 other people) perfectly.

**Comment by djerun** [comment]
>  Why don't you try or at least answer?

i did answer

**Comment by djerun** [comment]
> Sidenote: the travelynx tokens are no UUIDs because of the user id prefix. 

I shouldn't do this stuf at 3am

> If any of them are thinking that this validation is trivial, PRs are welcome to the project at any time. All I can tell is that the travelynx check-in is working for me (and at least 3 other people) perfectly.

well
```python
import re
import uuid
TOKEN = '12345-'+str(uuid.uuid4())
def is_valid(token: str):
    idx = token.find('-')
    try:
        uuid.UUID(token[idx+1:])
    except ValueError:
        return False
    except IndexError:
        return False
    id = token[:idx]
    return bool(re.fullmatch(r'[0-9]+', id))

is_valid(TOKEN)
is_valid(TOKEN+' ')
is_valid(' '+TOKEN)
is_valid('travel        '+TOKEN)
```
still seems trivial to me. whatever that translates to in kotlin

also the reason I closed tihs is because I uninstalled, disabling notifications for this now
